version: '3.8'

services:

  healthcare_service:
    image: healthcare_service
    container_name: healthcare_service
    build:
      context: .
      dockerfile: ./healthcare-service/Dockerfile
    restart: always
    ports:
      - ${HEALTHCARE_SERVICE_PORT}:${HEALTHCARE_SERVICE_PORT}
    environment:
      HEALTHCARE_DB_HOST: ${HEALTHCARE_DB_HOST}
      HEALTHCARE_DB_PORT: ${HEALTHCARE_DB_PORT}
      HEALTHCARE_SERVICE_PORT: ${HEALTHCARE_SERVICE_PORT}
      HEALTHCARE_SERVICE_HOST: ${HEALTHCARE_SERVICE_HOST}
    depends_on:
      - healthcare_db
    networks:
      - network
    volumes:
      - logs_volume:/logs

  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - network

  auth-service:
    image: jboss/keycloak:latest
    container_name: auth_service
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=
      - KEYCLOAK_CLIENT_ID=your-client-id
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
      - KEYCLOAK_REDIRECT_URL=http://auth-service:8080/callback
      - KEYCLOAK_ALLOWED_AUDIENCE=your-client-id
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
    ports:
      - 18080:8080
    depends_on:
      - auth-service-web

  auth-service-web:
    build: .
    container_name: auth_service_web
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - auth-service


  healthcare_db:
    image: mongo
    container_name: healthcare_db
    restart: on-failure
    networks:
      - network

volumes:

  logs_volume:

networks:
  network:
    driver: bridge